GET http://localhost:3016/todos/?status=TO%20DO

### API for TO DO  1

GET http://localhost:3016/todos/?priority=HIGH

### API for priority  2

GET http://localhost:3016/todos/?priority=HIGH&status=IN%20PROGRESS

### API for both priority and status  3

GET http://localhost:3016/todos/?search_q=Buy

### API for search_q  4

GET http://localhost:3016/todos/?category=WORK&status=DONE

### API for category and status  5

GET http://localhost:3016/todos/?category=HOME

### API for category 6

GET http://localhost:3016/todos/?category=LEARNING&priority=HIGH

### API for both category and priority  7

GET http://localhost:3016/todos/1/

### API 2 get todo via todoId

GET http://localhost:3016/agenda/?date=2021-12-12
